version: '3.4'

networks:
  ctfnet:

services:
  ctf:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ctfreverse
    environment:
      - ASPNETCORE_FLAG=HITS{4ddr3ss_1s_l3n1na_36_k0rpu5_no_2}
      - ASPNETCORE_DB_CONN=Server=db;Port=5432;Database=CtfDb;User ID=postgres;password=1234;
    ports:
      - "7000:80"
    restart: always
    networks:
      - ctfnet
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=CtfDb
    ports:
      - "5432"
    networks:
      - ctfnet
