---
# nginx installation
nginx_modules:
  - name: njs
    state: present

nginx_static_modules:
  - http_ssl_module
  - http_index_module

# nginx configuration
nginx_config_debug_output: true

nginx_config_main_template_enable: true
nginx_config_main_template:
  template_file: nginx.conf.j2
  deployment_location: /etc/nginx/nginx.conf
  backup: true
  config:
    main:
      load_module:
        - modules/ngx_http_js_module.so
      user:
        username: nginx
        group: nginx
      worker_processes: auto
      error_log:
        file: /var/log/nginx/error.log
        level: notice
      pid: /var/run/nginx.pid
      daemon: true
    events:
      worker_connections: 1024
    http:
      include: /etc/nginx/conf.d/*.conf
    stream:
      include:
        - /etc/nginx/conf.d/stream/*.conf

nginx_config_http_template_enable: true
nginx_config_http_template:
  - template_file: http/default.conf.j2
    deployment_location: /etc/nginx/conf.d/default.conf
    backup: true
    config:
      upstreams:
        - name: kt_ctfd
          servers:
            - address: "127.0.0.1:8080"
        - name: ctfd
          servers:
            - address: "127.0.0.1:8000"
      servers:
        - core:
            server_name: "hits-ctf.ru"
            listen:
              - port: 80
          rewrite:
            return:
              url: "https://hits-ctf.ru$request_uri"
        - core:
            server_name: "hits-ctf.ru"
            listen:
              - port: 443
                ssl: true
          ssl:
            certificate: /etc/letsencrypt/live/hits-ctf.ru/fullchain.pem
            certificate_key: /etc/letsencrypt/live/hits-ctf.ru/privkey.pem
          locations:
            - location: /
              proxy:
                pass: "http://ctfd"
        - core:
            server_name: "kt.hits-ctf.ru"
            listen:
              - port: 80
          rewrite:
            return:
              url: "https://kt.hits-ctf.ru$request_uri"
        - core:
            server_name: "kt.hits-ctf.ru"
            listen:
              - port: 443
                ssl: true
          ssl:
            certificate: /etc/letsencrypt/live/kt.hits-ctf.ru/fullchain.pem
            certificate_key: /etc/letsencrypt/live/kt.hits-ctf.ru/privkey.pem
          locations:
            - location: /
              proxy:
                pass: "http://kt_ctfd"

      proxy:
        http_version: 1.1
        set_header:
          - field: X-Real-Ip
            value: $remote_addr
          - field: X-Forwarded-For
            value: $proxy_add_x_forwarded_for
          - field: Host
            value: $proxy_host

# certbot configuration
certbot_admin_email: somnoynadno@yandex.ru

certbot_testmode: false
certbot_create_method: standalone
certbot_create_if_missing: true

certbot_certs:
  - domains:
      - hits-ctf.ru
  - domains:
      - kt.hits-ctf.ru

certbot_create_standalone_stop_services:
  - nginx
