version: '3.4'

networks:
  ctfnet:

services:
  ctf:
    build:
      context: .
      dockerfile: ./.Dockerfile
    container_name: sqlictf
    environment:
      - ASPNETCORE_FLAG=HITS{child_predator}
      - ASPNETCORE_INIT_CONN=Host=db;port=5432;Username=postgres;Password=ilikehex;
      - ASPNETCORE_DEFAULT_CONN=Host=db;port=5432;Username=postgres;Password=ilikehex;Database=testdb;
    ports:
      - "7001:80"
    restart: always
    networks:
      - ctfnet
    depends_on:
      - db
  
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ilikehex
      - POSTGRES_DB=testdb
    ports:
      - "5433"
    networks:
      - ctfnet
